version: "3.8"

services:
  zblog-user-core:
    build:
      context: ./zblog-user-core
      dockerfile: Dockerfile
    environment:
      - DB_URL=${DB_URL_USER}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=8092
      - COGNITO_ISSUER_URI=${COGNITO_ISSUER_URI}
      - POST_CORE_URL=${POST_CORE_URL}
      - INTERNAL_SHARED_SECRET=${INTERNAL_SHARED_SECRET}
      - S3_CORE_URL=${S3_CORE_URL}
    networks:
      - zblog-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/user/health"]
      interval: 30s
      retries: 3

  zblog-post-core:
    build:
      context: ./zblog-post-core
      dockerfile: Dockerfile
    environment:
      - DB_URL=${DB_URL_POST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_COGNITO_ISSUER_URI=${COGNITO_ISSUER_URI}
      - AWS_REGION=${AWS_S3_REGION}
      - S3_CORE_URL=${S3_CORE_URL}
      - PORT=8081
    networks:
      - zblog-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/post/health"]
      interval: 30s
      retries: 3

  zblog-comment-core:
    build:
      context: ./zblog-comment-core
      dockerfile: Dockerfile
    environment:
      - DB_URL=${DB_URL_COMMENT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_COGNITO_ISSUER_URI=${COGNITO_ISSUER_URI}
      - AWS_REGION=${AWS_S3_REGION}
      - S3_CORE_URL=${S3_CORE_URL}
      - POST_CORE_URL=${POST_CORE_URL}
    networks:
      - zblog-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/comment/health"]
      interval: 30s
      retries: 3

  s3-core:
    build:
      context: ./s3-core
      dockerfile: Dockerfile
    environment:
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_UPLOAD_EXPIRY_SECONDS=${AWS_S3_UPLOAD_EXPIRY_SECONDS}
      - AWS_S3_MAX_FILE_SIZE=${AWS_S3_MAX_FILE_SIZE}
      - LOGGING_LEVEL_ORG_SPRING_SECURITY=${LOGGING_LEVEL_ORG_SPRING_SECURITY}
      - AWS_COGNITO_ISSUER_URI=${COGNITO_ISSUER_URI}
      - SPRING_MVC_STATIC_PATH_PATTERN=${SPRING_MVC_STATIC_PATH_PATTERN}
    networks:
      - zblog-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/s3/health"]
      interval: 30s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - zblog-user-core
      - zblog-post-core
      - zblog-comment-core
      - s3-core
    networks:
      - zblog-net

networks:
  zblog-net:
    name: zblog-net
