version: "3.8"

services:
  zblog-user-core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=8092
      - COGNITO_ISSUER_URI=${COGNITO_ISSUER_URI}
      - POST_CORE_URL=${POST_CORE_URL}
      - INTERNAL_SHARED_SECRET=${INTERNAL_SHARED_SECRET}
      - S3_CORE_URL=${S3_CORE_URL}