version: "3.8"

services:
  zblog-comment-core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_COGNITO_ISSUER_URI=${COGNITO_ISSUER_URI}
      - AWS_REGION=${AWS_REGION}
      - S3_CORE_URL=${S3_CORE_URL}
      - POST_CORE_URL=${POST_CORE_URL}
