# docker-compose.yml
version: "3.8"

services:
  s3-core:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_S3_UPLOAD_EXPIRY_SECONDS=${AWS_S3_UPLOAD_EXPIRY_SECONDS}
      - AWS_S3_MAX_FILE_SIZE=${AWS_S3_MAX_FILE_SIZE}
      - LOGGING_LEVEL_ORG_SPRING_SECURITY=${LOGGING_LEVEL_ORG_SPRING_SECURITY}
      - AWS_COGNITO_ISSUER_URI=${AWS_COGNITO_ISSUER_URI}
      - SPRING_MVC_STATIC_PATH_PATTERN=${SPRING_MVC_STATIC_PATH_PATTERN}
