name: Deploy Frontend to Heroku

on:
  push:
    branches: [main]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: zblog-frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js Buildpack for Frontend
        run: heroku buildpacks:set heroku/nodejs

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build frontend
        run: npm run build

      - name: Set environment variables
        run: |
          echo NEXT_PUBLIC_COGNITO_AUTHORITY=${{ secrets.NEXT_PUBLIC_COGNITO_AUTHORITY }} >> .env
          echo NEXT_PUBLIC_COGNITO_CLIENT_ID=${{ secrets.NEXT_PUBLIC_COGNITO_CLIENT_ID }} >> .env
          echo NEXT_PUBLIC_COGNITO_REDIRECT_URI=${{ secrets.NEXT_PUBLIC_COGNITO_REDIRECT_URI }} >> .env

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_FRONTEND_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false